# Generated by Django 4.2.27 on 2026-02-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="checkin_end",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bracket",
            name="day",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bracket",
            name="start_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
