# Generated by Django 4.2.27 on 2026-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_bracket_checkin_end_bracket_day_bracket_start_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="room",
            name="rows",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="room",
            name="tables_per_row",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="table",
            name="orientation",
            field=models.CharField(
                choices=[("horizontal", "Horizontal"), ("vertical", "Vertical")],
                default="horizontal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="position_col",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="table",
            name="position_row",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("free", "Libre"),
                    ("occupied", "Occupee"),
                    ("maintenance", "Maintenance"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_number",
            field=models.IntegerField(unique=True),
        ),
    ]
