# Generated by Django 4.2.27 on 2026-02-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_alter_table_unique_together_room_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="bye_players",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bracket",
            name="pool_qualifiers",
            field=models.IntegerField(default=2),
        ),
    ]
