# Generated by Django 4.2.27 on 2026-02-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0005_useraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="forfeit_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forfeit_matches",
                to="tournament.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="is_forfeit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player2",
                to="tournament.player",
            ),
        ),
    ]
