# Generated by Django 4.2.27 on 2026-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0006_match_forfeit_player_match_is_forfeit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="dotation_finalist",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="bracket",
            name="dotation_quarter",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="bracket",
            name="dotation_semi",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="bracket",
            name="dotation_winner",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="playerbracketregistration",
            name="checkin_status",
            field=models.CharField(
                blank=True,
                choices=[("P", "Present"), ("A", "Absent")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="buvette_col",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="room",
            name="buvette_row",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="room",
            name="entrance_col",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="room",
            name="entrance_row",
            field=models.IntegerField(default=-1),
        ),
    ]
