# Generated by Django 4.2.27 on 2026-02-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0007_add_dotation_checkin_room_markers"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="wc_markers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
