# Generated by Django 4.2.27 on 2026-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0008_add_wc_markers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="buvette_col",
        ),
        migrations.RemoveField(
            model_name="room",
            name="buvette_row",
        ),
        migrations.RemoveField(
            model_name="room",
            name="entrance_col",
        ),
        migrations.RemoveField(
            model_name="room",
            name="entrance_row",
        ),
        migrations.AddField(
            model_name="room",
            name="buvette_markers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="entrance_markers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
