# Generated by Django 4.2.27 on 2026-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0009_markers_to_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="arrow_markers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="rotation",
            field=models.IntegerField(default=0),
        ),
    ]
