# Generated by Django 4.2.27 on 2026-04-13 22:09

import secrets
from django.db import migrations, models
import django.db.models.deletion


def generate_qr_tokens(apps, schema_editor):
    Registration = apps.get_model('tournament', 'PlayerBracketRegistration')
    for reg in Registration.objects.all():
        reg.qr_token = secrets.token_urlsafe(32)
        reg.save(update_fields=['qr_token'])


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0010_add_arrow_rotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items/"),
        ),
        migrations.AddField(
            model_name="playerbracketregistration",
            name="dossard_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerbracketregistration",
            name="qr_token",
            field=models.CharField(blank=True, max_length=64, default=''),
        ),
        migrations.RunPython(generate_qr_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="playerbracketregistration",
            name="qr_token",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="playerbracketregistration",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="playerbracketregistration",
            name="stripe_session_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="room",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="tournament.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("player", "Joueur"),
                    ("admin", "Administrateur"),
                    ("juge_arbitre", "Juge-Arbitre"),
                ],
                default="player",
                max_length=20,
            ),
        ),
    ]
