# Generated by Django 4.2.27 on 2026-04-13 22:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0011_menuitem_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsAdapterConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "adapter_type",
                    models.CharField(
                        choices=[
                            ("test", "Test (Console)"),
                            ("ovh", "OVH SMS"),
                            ("twilio", "Twilio"),
                            ("free_mobile", "Free Mobile"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "default_sender",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="playernotificationsubscription",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="playernotificationsubscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="playernotificationsubscription",
            name="subscriber_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="playernotificationsubscription",
            name="subscriber_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="playernotificationsubscription",
            name="subscriber_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("match_created", "Match créé"),
                    ("match_started", "Match commencé"),
                    ("table_assigned", "Table assignée"),
                    ("match_blocked", "Match bloqué"),
                    ("match_unblocked", "Match débloqué"),
                    ("sms_admin", "SMS Admin"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=20)),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("message", models.TextField()),
                ("sender", models.CharField(blank=True, default="", max_length=50)),
                (
                    "adapter_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Envoye"),
                            ("failed", "Echoue"),
                            ("pending", "En attente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="tournament.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
