# Generated by Django 4.2.27 on 2026-05-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0013_default_sms_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsadapterconfig",
            name="adapter_type",
            field=models.CharField(
                choices=[
                    ("test", "Test (Console)"),
                    ("ovh", "OVH SMS"),
                    ("twilio", "Twilio"),
                    ("free_mobile", "Free Mobile"),
                    ("smpp", "SMPP (SMPPSim)"),
                ],
                max_length=50,
            ),
        ),
    ]
